name: delni_app
description: تطبيق دلني للإعلانات المبوبة

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  path: ^1.9.0
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.2
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  location: ^5.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/ad_sample.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png"

